//
// EPITECH PROJECT, 2020
// AREA
// File description:
// Constants
//

export const EN = {
    SIGN_IN: `Sign in`,
    SIGN_UP: `Sign up`,
    SIGN_IN_GOOGLE: `Sign in with Google`,
    SIGN_UP_GOOGLE: `Sign up with Google`,
    REGISTER_POPUP: `Don't have an account ? Sign up`,
    LOGIN_POPUP: `Already have an account? Sign in`,
    AFTER_REGISTER_MSG: `You're now registered, please confirm your email account and then login`,
    WRONG_EMAIL: `Wrong email address`,
    EMAIL_ADDRESS: `Email Address`,
    YOUR_EMAIL_ADDRESS: `Your email Address`,
    LOGOUT: `Logout`,
    PASSWORD: `Password`,
    PASSWORD_CONFIRMATION: `Password confirmation`,
    GOOGLE_PROCESSING_REGISTER: `Please wait for Google signing in process...`,
    GOOGLE_NO_ACCOUNT: `You don't have an account, would you like to register with your Google account ?`,
    GOOGLE_BUTTON_REGISTER: `Register with Google`,
    HELLO: `Hello `,
    HELLO_NOSPACE: `Hello`,
    MODAL_ADD: `ADD`,
    MODAL_CANCEL: `CANCEL`,
    MODAL_UPDATE: `UPDATE`,
    MODAL_ADD_WIDGET: `Add an AREA`,
    MODAL_SELECT_WIDGET: `Select a reaction`,
    MODAL_SELECT_SERVICE: `Select a service`,
    MODAL_UPDATE_WIDGET: `Update a widget`,
    MODAL_SUBSCRIBE_SERVICE: `To subscribe to a service, please select a service and its trigger parameters, a reaction and its parameters`,
    REACTION: `Reaction`,
    ACTION: `Action`,
    STATS: `Stats`,
    AREA_INFORMATIONS: `Area Informations`,
    SERVICE: `Service`,
    DESCRIPTION: `Description of the AREA`,
    NAME: `Name of the AREA`,
    RELOAD_LINKS: 'RELOAD LINKS',
    LINKED: 'LINKED',
    LIST_OF_YOUR_AREAS: `List of your AREAs`,
    CONNECT_WITH: 'CONNECT WITH',
    ENTER_NAME_DESC: 'Please enter a name and a description for the AREA',
    ADD_REACTION: `ADD A REACTION`,
    REMOVE_LAST_REACTION: `REMOVE LAST REACTION`,
    ACTION_INFORMATION: `Action informations`,
    ACTION_PARAMETERS: `Action parameters`,
    REACTION_INFORMATION: `Reaction informations`,
    REACTION_PARAMETERS: `Reaction parameters`,
    ACCOUNT_INFORMATION: `Account informations`,
    ACCOUNT_PARAMETERS: `Account parameters`,
    ACCOUNT_LINKS: `Account links`,
};

export const FR = {
    SIGN_IN: `Se connecter`,
    SIGN_UP: `S'inscrire`,
    SIGN_IN_GOOGLE: `Se connecter avec Google`,
    SIGN_UP_GOOGLE: `S'inscrire' avec Google`,
    REGISTER_POPUP: `Je n'ai pas de compte ? S'inscrire`,
    LOGIN_POPUP: `J'ai déjà un compte ? Se connecter`,
    AFTER_REGISTER_MSG: `Vous êtes maintenant inscrit, veuillez confirmer votre compte de messagerie puis vous connecter`,
    WRONG_EMAIL: `Mauvaise adresse email`,
    EMAIL_ADDRESS: `Adresse Email`,
    YOUR_EMAIL_ADDRESS: `Votre adresse email`,
    LOGOUT: `Se déconnecter`,
    PASSWORD: `Mot de passe`,
    PASSWORD_CONFIRMATION: `Confirmation mot de passe`,
    GOOGLE_PROCESSING_REGISTER: `Veuillez attendre le processus de connexion à Google...`,
    GOOGLE_NO_ACCOUNT: `Vous n'avez pas de compte, souhaitez-vous vous inscrire avec votre compte Google ?`,
    GOOGLE_BUTTON_REGISTER: `Inscrivez-vous avec Google`,
    HELLO: `Bonjour `,
    HELLO_NOSPACE: `Bonjour`,
    MODAL_ADD: `Ajouter`,
    MODAL_CANCEL: `Annuler`,
    MODAL_UPDATE: `Mettre à jour`,
    MODAL_ADD_WIDGET: `Ajouter une AREA`,
    MODAL_SELECT_WIDGET: `Sélectionner une réaction`,
    MODAL_SELECT_SERVICE: `Sélectionner un service`,
    MODAL_UPDATE_WIDGET: `Mettre à jour le widget`,
    MODAL_SUBSCRIBE_SERVICE: `Pour vous abonner à un service, veuillez sélectionner un service et ses paramètres de déclenchement, ainsi qu'une réaction et ses paramètres`,
    REACTION: `Réaction`,
    ACTION: `Action`,
    STATS: `Statistique`,
    AREA_INFORMATIONS: `Informations sur l'AREA`,
    SERVICE: `Service`,
    DESCRIPTION: `Description de l'AREA`,
    NAME: `Nom de l'AREA`,
    RELOAD_LINKS: 'RECHARGER LES LIENS',
    LINKED: 'LIÉ',
    LIST_OF_YOUR_AREAS: `Liste de vos AREAs`,
    CONNECT_WITH: 'SE CONNECTER AVEC',
    ENTER_NAME_DESC: `Veuillez saisir un nom et une description pour l'AREA`,
    ADD_REACTION: `AJOUTER UNE RÉACTION`,
    REMOVE_LAST_REACTION: `SUPPRIMER LA DERNIÈRE RÉACTION`,
    ACTION_INFORMATION: `Informations de l'action`,
    ACTION_PARAMETERS: `Paramètres de l'action`,
    REACTION_INFORMATION: `Informations de la réaction`,
    REACTION_PARAMETERS: `Paramètres de la réaction`,
    ACCOUNT_INFORMATION: `Informations du compte`,
    ACCOUNT_PARAMETERS: `Paramètres du compte`,
    ACCOUNT_LINKS: `Comptes liés`,
};

export const ES = {
    SIGN_IN: `Conectarse`,
    SIGN_UP: `Inscribirse`,
    SIGN_IN_GOOGLE: `Inicia sesión con Google`,
    SIGN_UP_GOOGLE: `Registrarse 'con Google`,
    REGISTER_POPUP: `No tengo una cuenta ? Inscribirse`,
    LOGIN_POPUP: `Ya tengo una cuenta ? Conectarse`,
    AFTER_REGISTER_MSG: `Ahora está registrado, confirme su cuenta de correo electrónico y luego inicie sesión`,
    WRONG_EMAIL: `Dirección de correo errónea`,
    EMAIL_ADDRESS: `Correo electrónico`,
    YOUR_EMAIL_ADDRESS: `Tu correo electrónico`,
    LOGOUT: `Desconectarse`,
    PASSWORD: `Contraseña`,
    PASSWORD_CONFIRMATION: `Confirmación de contraseña`,
    GOOGLE_PROCESSING_REGISTER: `Espere el proceso de inicio de sesión de Google...`,
    GOOGLE_NO_ACCOUNT: `No tiene una cuenta, ¿le gustaría registrarse con su cuenta de Google ?`,
    GOOGLE_BUTTON_REGISTER: `Regístrese con Google`,
    HELLO: `Hola `,
    HELLO_NOSPACE: `Hola`,
    MODAL_ADD: `Agregar`,
    MODAL_CANCEL: `Anular`,
    MODAL_UPDATE: `Poner al día`,
    MODAL_ADD_WIDGET: `Agregar un área`,
    MODAL_SELECT_WIDGET: `Seleccione una reacción`,
    MODAL_SELECT_SERVICE: `Seleccione un servicio`,
    MODAL_UPDATE_WIDGET: `Actualizar el widget`,
    MODAL_SUBSCRIBE_SERVICE: `Para suscribirse a un servicio, seleccione un servicio y sus parámetros de activación, así como una reacción y sus parámetros`,
    REACTION: `Reacción`,
    ACTION: `Acción`,
    STATS: `Estadístico`,
    AREA_INFORMATIONS: `Información del área`,
    SERVICE: `Servicio`,
    DESCRIPTION: `Descripción de AREA`,
    NAME: `Nombre del área`,
    RELOAD_LINKS: 'RECARGAR ENLACES',
    LINKED: 'ATADO',
    LIST_OF_YOUR_AREAS: `Lista de sus AREAs`,
    CONNECT_WITH: 'CONECTAR CON',
    ENTER_NAME_DESC: `Introduzca un nombre y una descripción para el AREA`,
    ADD_REACTION: `AÑADIR UNA REACCIÓN`,
    REMOVE_LAST_REACTION: `BORRAR ÚLTIMA REACCIÓN`,
    ACTION_INFORMATION: `Action informations`,
    ACTION_PARAMETERS: `Action parameters`,
    REACTION_INFORMATION: `Reaction informations`,
    REACTION_PARAMETERS: `Reaction parameters`,
    ACCOUNT_INFORMATION: `Account informations`,
    ACCOUNT_PARAMETERS: `Account parameters`,
    ACCOUNT_LINKS: `Account links`,
};


export const LANG = EN;
