##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## makefile
##

all:
	make -C generator
	make -C solver

clean:
	make -C generator clean
	make -C	solver clean

fclean:
	make -C	generator fclean
	make -C	solver fclean

re:
	make -C	generator re
	make -C	solver re

.PHONY: all clean re fclean
